# config
web:
  host: "localhost"
  port: 7071
websocket:
  path: "ws"
telnet:
  host: "localhost"
  port: 5566
  charset: "gbk"
log:
  console:
    out: "stdout"
    level: "debug"
    encoder:
      name: "console"
      time-format: "2006-01-02T15:04:05"
  file:
    out: "tmp/log/app.log"
    level: "info"
    encoder:
      name: "json"
      time-format: "RFC3339"
    rotate: true
    # megabytes
    max-size: 10
    max-days: 7
    max-backups: 10
