name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        mkdir web/dist
        touch web/dist/placeholder.embed
    - name: Build
      run: go build -v .
